### PR TITLE
Bms rms interface

### PR DESCRIPTION
**Pull request by dawiggleman**
Create BMS, RMS, Precharge board interfaces, and pump control circuit on avionics board. Add component F2570CT in misc to replace 2A 0402 outdated fuse.

### CODE REVIEW

**Comment by rcastle1** [comment]
BMS Interface: 

image

* Is this going to the motor controller or the BMS? It would be good to allow the system to operate with the motor controller powered or the BMS powered, but not necessarily both (for low voltage testing only, obviously)

image

* Consider splitting this into two devices and routing out more signals from the BMS. Even signals like CAN2 and always on power could be decent. 
* Route out all GNDs from BMS, want to couple relay outputs with a GND, if possible. I don't really like the text in place of the net, but I get what you're getting at. 
* Consider putting the BMS PWR nets closer to each other. Less chance of a short if your power pins are on the ends, rather than throughout the connector (Think about when you count pins, you are more likely to miss a row at the beginning than at either end)
* I'd describe what the MPO1 actually is allocated for. 
* What is the drive strength for the multipurpose signals? Is it enough to drive multiple LEDs? 

image

* Let's just add a switch for this 

Misc.
* Add a separate connector for charger CAN and shutdown circuit output for charging. Will reduce the amount of external components we have on the charging side. Also think about where termination resistors will be at in that use case
* In general, think about termination resistors. This schematic should start defining that. Does BMS and motor controller can be configured with either EEPROM (motor controller) or by wiring (BMS) to have a termination resistor, and we need exactly 2 for the configuration, and they should be as far apart as possible. 


Motor controller interface
image
* Similar thing here with moving the PWR pins. Are these the only outputs we need / could want from the motor? 
* Can we rename RMS_7_Relay2 with the actual function? 

image
* I'd add some bulk cap to this after the fuse with a note to keep it close to the connector

image
* You always want to have the same number of PWR and GND nets. Does this match up with the interface on the prcharge board itself so we can use a pre-made harness? 

image
* FET can only do ~2A DC at 24V. Is that sufficient for the pump? 
image
* Should also edit that footprint to and make the actual component name shown 
* Add manufacturer part search info to the FET (legacy component, speaking of that, one of these days we should go through the library and make sure all components are up to our current standards)
* What is the current limit on the fuse? Not just this one. It's good to be able to tell by just looking at the component. 


Misc. 
* If we can figure out how to default display capacitance rated voltage and thermal rating (X7R, NP0, X5R, etc) and resistor tolerance % that'd be awesome. Going through each component individually and setting that has prevented me from doing that, but it would be awesome as sometimes I've caught myself using some of the default 10V caps on VBUS.

**Comment by dawiggleman** [comment]
@rcastle1 Ready for review, couple notes:

-When the power / gnd pins look arbitrary, they're made so they are actually right next to each other, but on top/bottom of the connector.
-The precharge board interface has an unequal number of PWR and GND pins because many of the other pins are positive voltage pins, which all have to use the same GND (along with the 24V power)
-Added a lot of notes to make thought process/ purpose of things more clear for down the road and other readers

**Comment by brtobin** [comment]
CAN_pic
Is this the terminating resistor for the CAN2 line? Do we have one set up, as well for CAN1? I think I might see a note about it under the charge enable section, but I'm not sure

Also, did we get the bulk capacitor added?

**Comment by dawiggleman** [comment]
Yes, that's for the CAN2 line. Theres a termination resistor for CAN1 on a switch in the upper right corner of that schematic that will be used when not in a charging state, and not used when in a charging state

**Comment by dawiggleman** [comment]
Yes, I added capacitors to the devices that will be using the 12V stepped down power

**Comment by rcastle1** [comment]
image
Short

**Comment by rcastle1** [comment]
I'd recommend putting the termination resistor as close to the transceiver as possible on the schematic. Watch out for logic levels on that front. 

Add some bulk cap to BMS PWR

holdup calc for the shutdown circuit is wrong. Get rid of the R? underneath C7 and swap the cap with a larger cap. 2*12*.25/0.9*0.1/(12)^2 = ~4mF for 1s hold up. That's a lot, but we should get rid of that resistor and up the capacitance.  FSAE rules go up to 250ms, but that's a lot of bulk cap
image

**Comment by dawiggleman** [comment]
@rcastle1 where does that equation on hold up capacitance come from?

**Comment by dawiggleman** [comment]
Added 400uF of capacitance for holdup time of 50ms

**Comment by rcastle1** [comment]
https://www.electronicdesign.com/power/calculate-hold-capacitor-size-switching-linear-regulators they do a hold up calc here. I'm thinking several of those al poly caps just to get to 400uF isn't worth it, might have to adjust at the layout stage. 

main_io.PrjPcb is in conflict on this branch and master, so that will need to be resolved before merging. Likely due to extra schematic sheets being added and saved.

**Comment by dawiggleman** [comment]
Fixed merge conflict

**Review by rcastle1 — COMMENTED** [review]
BMS Interface:

* Thermistor Power and CAN connector should be merged into a single connector, so we have a 1-1 connection. 

* Eventually, let's throw all of the connectors on the connector sheet. Simplifies it later on when you only want to look for pinouts. 

RMS Interface: 
* This is configured incorrectly. The high current path from the pump should just go from 24V through the fuse, through the connector, through the relay, and to ground, not through the opto. The opto is meant to do logic/power level shifting and has a 50mA limit, so it's only used for the coil driver. Is S? used for an always on pump? If so, I'd recommend eliminating S? and just using a jumper to short out the contacts of K?. It uses less power and is just going to be simpler, if we think we need this feature. 
image


* You can name the nets "PUMP_POS" and "PUMP_RET" instead of the blue text. Depending on your company, you may have to name every net.

* More of a library thing, but I'd consider making the fuse voltage and current ratings visible rather than the part number. Makes it easier to quickly determine if a component is appropriately sized or not. I want to do this with the bulk capacitor as well. 

* For readability, consider merging these into a single block. (connect RMS_PWR by wire, rather than by net.) 
image

* Consider renaming nets "V-POS12V_RMS_PWR" or something similar to fit the power naming convention. 

RTC: 
* Rename INT/SQW net to INT_SQW. "/" is hard to wildcard search for. 

* I didn't change any electrical connections, but I re-arranged the schematic to make it a bit more readable. I'm not going to save, but this style is a bit more clean in my opinion. 
Before: 
image
After: 
image

* Add bulk cap on Vbatt.

**Comment by rcastle1** [comment]
bt_avionics review: 

* Slide this guy on over there a wee bit. image

* Add a low pass filter
image
* Follow the naming convention for telemetry channels. TELEM_V_xxx TELEM_I_xxx
* Change all of the VPOS-5V to V-POS5V to follow the convention. 

UART: 
* Missing VCC connection (similar issue on braking IO) 
* Does the footprint match the part that's linked? We ran into that issue on the braking IO board. 
image

CAN: 
* Add a Csplit cap since we've already split up the 120 into two 60Ohm resistors. 

GPIO: 
* I'd rename this from generic.SchDoc to GPIO.SchDoc. Remember to delete the old file name from the project AND the folder, otherwise when we inevitably re-add all of the SchDocs in the folder to the project we don't inadvertently add duplicates. 
* With any I2C device, I like to write the expected address to the schematic in text, just so it's easy to reference later on and make it easier for the controls team. 

ADC: 
* Verify this circuit on the braking IO boards before committing to it on this board 
* Add title and metadata below. 

Battery interface: 
I'm assuming this is still in progress based on latest slack message. lmk if we should talk though this. I know I pushed for it, but we should think about if it's necessary.

**Comment by dawiggleman** [comment]
Made updates on BMS_RMS interface and BT_Avionics
Couple notes on non-changes:
-The MAX232's have 5V on the VCC pin
-Footprint on MAX232 matches linked part
-Going to wait until later to change generic.schdoc to GPIO, to reduce possible merge conflicts with project file
-I2C devices have their address underneath them

**Pull request merged**
