### PR TITLE
Librarian 2

### PR DESCRIPTION
**Pull request by dawiggleman**
Add Components:
TPS54560BQDDARQ1 to ic.schlib
SRR1280-4R7Y to inductor.schlib

Move DIODE GEN PURP 200V 2A SOD123FL from IC to misc library
Delete obsolete mosfet in misc library

### CODE REVIEW

**Comment by rcastle1** [comment]
image
It's ok to put pins out of order if it makes the schematic more clear. I'd recommend something like this rather than all of the pins right on top of each other and in order. Inputs on the left, outputs on the right (for the most part). Think about what each of the pins are actually doing and design your symbol around that. The datasheet has a good example.  Also, giving 100mil between components makes it easier to place a resistor or cap in line.

**Comment by rcastle1** [comment]
inductor looks good

**Review by rcastle1 — CHANGES_REQUESTED** [review]
Testing out the review feature. Might switch from commenting to review.

**Comment by dawiggleman** [comment]
Changes made

**Comment by dawiggleman** [comment]
image

**Review by rcastle1 — CHANGES_REQUESTED** [review]
I would align the pins on the right with the pins on the left, as below but it's ok as is.
image

I'd also hide the supplier part number and show the manufacturer part number by default. It's just a lot easier to identify based on the manufacturer PN. (TPS and LM are TI power supplies, LTC are linear tech, etc, OPA are TI op amps) just easier to quickly identify components and makes us less tied to one supplier. 

image

Move this silkscreen circle as it will just get cut off and give you a silk-soldermask clearance rule violation

**Comment by dawiggleman** [comment]
Updated!

**Pull request merged**
