### PR TITLE
Battery protection

### PR DESCRIPTION
**Pull request by dawiggleman**
Finished precharge  board schematics & cell interface on main avionics board, additional temporary library with all new necessary components for precharge board and battery interface.

### CODE REVIEW

**Comment by rcastle1** [comment]
@dawiggleman do you know what the change to the resistor library was?

**Comment by dawiggleman** [comment]
No, I did not intend to change that library @rcastle1

**Comment by rcastle1** [comment]
Just going to list out some updates:

image
* "Avionics"


image
* Let's add the actual manufacturer part data. Same with the flyback diode. I know this part is re-used, but we should get the library updated. 

image
* Usually want to avoid this type of overhung connection. When you compile, you might get a floating net violation and it can be annoying. Also, could probably just move GND over rather than the awkward C shape. 

image
* Usually avoid using a "+" in a net name. Some of the automated net checking tools don't like it. 

image
* A few things here: 
* We need to isolate HV GND and LV GND, even though they're still separate from the battery GND.
* Let's edit this DCDC footprint and make the pinout a little cleaner. 

image
* We'll want to put a No connect DRC waiver for the disconnect pin. 

* Let's set up blanket design rules for spacing. Any HV components should get a blanket rule applied to them for proper spacing. 

* I usually try to put as much info in the schematics as possible. Have you figured out the layer stackup, current requirements, trace width requirements for the high current path? Last I heard it was still a little unclear if this board will actually work. 

image
* Small thing, but I'd pull this block down to keep lines straight. 

image
* Need to update this sch symbol to have a ? in the default part

* High current connectors have minimum order quantity of 80 at digikey, will need to go to mouser. 
* Also, these are still a bit borderline, given 350A with a 30% derating is only 245A. I think that's sufficient for our duration though. 

* Can you spec out the screw that will connect to the contactor as well? 

* Double check your capacitor footprint. Pads are a bit narrow https://www.avx.com/download/software/literature/AVX-Footprint-Library.pdf
image
image
* Will probably get a annular ring violation with the part (contactor footprint)

image

* Adjust z-axis offset 

* Do the contactors actually have the aux outputs? 

* I'd throw another HV indicator light connector on as well. I like the board mount LED selection, but maybe go with something surface mount. 

* We'll want to number all of these parts before importing to a SCH. Tools>Annotation>Annotate Schematics (or annotate quietly if you want)

Overall, great job. These are all fairly small updates. I'm definitely still worried the current requirements and our traces. Setting up the HV and LV blanket rules is also going to be important. https://www.altium.com/documentation/altium-designer/specifying-design-requirements-with-design-directives-ad?version=19.0

Also if you could revert the resistor library it will make it easier to merge. I'll get the libraries updated after the updates.

**Comment by rcastle1** [comment]
I'll merge this when I get a chance, probably tomorrow

**Comment by dawiggleman** [comment]
@rcastle1 possible to review and accept? Fixed merge conflicts that were present

**Review by rcastle1 — APPROVED** [review]

**Comment by rcastle1** [comment]
Merged, but we will still need to merge the libraries manually.

**Pull request merged**
