### PR TITLE
Rtc

### PR DESCRIPTION
**Pull request by dawiggleman**
Create and complete RTC schematic, will need to integrate I2C and output signals with MCU/beaglebone once merged.

Created components:
BU2032SM-JJ-GTR in Misc.schlib
CR2032VP in misc.schlib
-both for needed coin cell

### CODE REVIEW

**Comment by dawiggleman** [comment]
Since I edited the libraries already on this branch, I made another update to the MAX232DWR in ic.schlib to update with the correct component parameters

**Comment by dawiggleman** [comment]
Comments from Brianna:
Looks good, some things looking at as I go:
That 32kHz line, should it be named that or is there like a better name for the actual signal that will feed to that. I'm just not sure of the convention
For the BB we had the lines had the node closest to SCL and SDA (before the resistor) named in case we wanted to use those for testing or if there was an error I think. Do we want to do that here?
How was the pull-up resistor values calculated for the INT and 32kHz nets, just standard? Also do we need pullups on the I2C SCL and SCA lines? I think on the datasheet it said you can do Tr/CB

**Comment by dawiggleman** [comment]
Reply from me:

The 32kHz line is a 32kHz line output from the RTC. Not sure if we'll actually use it, but it's there for now.

I don't think we'll need separate nodes on any I2C devices like the RTC for testing like we do on the beaglebone, primarily because the beaglebone is going to function as the "master"  and all the other devices will act as slaves and will only respond once called upon by the master.

The I2C bus will only need one set of pull-up resistors, and we can put those right off the beaglebone.

10K is a pretty standard pull up resistor value all around, but you are correct that it is a function of the frequency you are operating at and the capacitance of the bus. Below is the reference I used for the I2C specifically. I found that the value should be between 1533 ohms and 20k ohms.
32khz is relatively slow, so the 10K will work on that as well.

image

**Comment by rcastle1** [comment]
RTC_RST should be named RTC_RST_n to indicate polarity (easier on the controls end of things)

10k is fine for I2C. For reference, this is my favorite calculator document that gives you a pretty good idea for what's actually going on and what waveforms look like: http://www.ti.com/lit/an/slva689/slva689.pdf

We are powering off of the 5V rail, but the coin cell is 3V nominally. Did you look into any issues that might come up with this? 

https://www.adafruit.com/product/2922 This guy has an SD card built in. @ezraboley @rdaruwala did you want this?

**Comment by dawiggleman** [comment]
Made net change, switched main power to 3.3 from beaglebone since it is available. Regardless, the device just switches between power supplies depending on their voltage via this table:

image

**Review by rcastle1 — APPROVED** [review]

**Pull request merged**
