### PR TITLE
Librarian

### PR DESCRIPTION
**Pull request by dawiggleman**
Create RTC & pushbutton footprint, fix footprint on 1N4148WQ-7-F. Save all design files.

### CODE REVIEW

**Comment by rcastle1** [comment]
RTC: Properties look good, but the symbol needs to be drawn in the SchLib 

image

Any ideas what this is? 
image

Where is the push button?

It would also be good to list in the pull request exactly what components were added/modified

**Comment by dawiggleman** [comment]
Whups, accidentally made another component with symbol and footprint after pulling parameters. Should be fixed now.

**Comment by dawiggleman** [comment]
Components added:
DS3231 to ic.Schlib
K12SCS1.55NOLFTX to misc.Schlib

Components Modified:
1N4148WQ-7: Correct footprint

**Comment by rcastle1** [comment]
Changes look good. It's not a big deal, but I prefer rectangular SMD pads over the curved but that's more for consistency / import into other CAD tools. 

I made a couple of edits to this symbol.
* Spread out the pins which we know we will connect to
* Added "/SQW" to pin 3. The square wave may not be used for this particular design, but maybe it would be in the future. 
* Added the bar over RST to indicate active low
image

I also fixed up a couple of unrelated existing components.

**Review by rcastle1 — APPROVED** [review]

**Pull request merged**
